### ISSUE TITLE
Using in frontend: ReferenceError: process is not defined

### ISSUE THREAD

**Issue by suenot** [mtvkand/invest-nodejs-grpc-sdk#6]
Получил ошибку при попытке вызывать метод на фронтенде. Надеюсь, что проблема не из-за arm mac m1.
```
logging.ts:35 Uncaught ReferenceError: process is not defined
    at src/invest-nodejs-grpc-sdk/node_modules/@grpc/grpc-js/build/src/logging.js (logging.ts:35:22)
    at __require (chunk-M5PF3ZFT.js?v=4daefa91:28:50)
    at src/invest-nodejs-grpc-sdk/node_modules/@grpc/grpc-js/build/src/metadata.js (metadata.ts:19:1)
    at __require (chunk-M5PF3ZFT.js?v=4daefa91:28:50)
    at src/invest-nodejs-grpc-sdk/node_modules/@grpc/grpc-js/build/src/call-credentials.js (call-credentials.ts:18:1)
    at __require (chunk-M5PF3ZFT.js?v=4daefa91:28:50)
    at src/invest-nodejs-grpc-sdk/node_modules/@grpc/grpc-js/build/src/index.js (index.ts:25:1)
    at __require (chunk-M5PF3ZFT.js?v=4daefa91:28:50)
    at dep:@grpc_grpc-js:1:16
```

**Comment by mtvkand** [comment]
Нужно немного больше подробностей. Какой метод и как вызывался. Если была попытка использовать это на фронтенде , то библиотека grpc-js написана только для nodejs.

**Comment by suenot** [comment]
> Какой метод и как вызывался.

Ошибка была в createSdk при запуске на vue 3.

> Если была попытка использовать это на фронтенде , то библиотека grpc-js написана только для nodejs.

Ясно. Тогда можно закрывать issue.
